name: opencv-demo-ogra
version: '0.1'
base: core20
type: app
summary: A little face recognition test
description: |
  A simple OpenCV demo snap, shipping with three python based demos
    - opencv-demo-ogra.eyedetect - demo eye detection
    - opencv-demo-ogra.facedetect - demo face detection
    - opencv-demo-ogra.vidcapture - just a simple video capture demo
  please make sure to run
    sudo snap connect opencv-demo-ogra:camera
  to allow the demo to access your webcam

grade: stable
confinement: strict
compression: lzo

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/fonts:
    bind: $SNAP/gnome-platform/usr/share/fonts
  /usr/local/share/fonts:
    bind: $SNAP/gnome-platform/usr/share/fonts

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  daemon:
    command: usr/local/bin/x11_kiosk_launch $SNAP/snap/command-chain/desktop-launch $SNAP/bin/launcher
    command-chain:
      - env-setup
    daemon: simple
    extensions: [ gnome-3-38 ]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas
      PYTHONPATH: $SNAP/usr/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages
      GTK_USE_PORTAL: 0
    plugs:
      - camera
      - hardware-observe
      - home
      - login-session-control
      - network
      - network-bind
      - opengl
      - process-control
      - wayland
  classic:
    command: bin/launcher
    extensions: [ gnome-3-38 ]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$SNAP/usr/lib/x86_64-linux-gnu/atlas
      PYTHONPATH: $SNAP/usr/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages
      DISABLE_WAYLAND: 1
    plugs:
      - camera
      - home
      - network
      - network-bind
      - opengl
      - process-control
      - wayland
  v4l2-ctl:
    command: usr/bin/v4l2-ctl
    plugs:
      - camera
      - home

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv.git
    source-tag: 4.6.0
    source-depth: 1
    cmake-parameters:
      - -DINSTALL_C_EXAMPLES=ON
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DBUILD_EXAMPLES=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DOPENCV_EXTRA_MODULES_PATH=contrib/modules
      - -DWITH_JASPER=ON
    override-build: |
      git-force-clone -b 4.x https://github.com/opencv/opencv_contrib.git contrib
      snapcraftctl build
    build-packages:
      - libjpeg-dev
      - libtiff5-dev
      - libpng-dev
      - libpng16-16 
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libatlas-base-dev
      - gfortran
      - python3-dev
      - python3-numpy
      - git-extras
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatlas3-base
      - libatspi2.0-0
      - libavcodec-extra58
      - libavformat58
      - libavutil56
      - libbluray2
      - libboost-filesystem1.67.0
      - libboost-system1.67.0
      - libcairo2
      - libcairo-gobject2
      - libcapnp-0.7.0
      - libdatrie1
      - libdc1394-22
      - libepoxy0
      - libexif12
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgl1-mesa-dri
      - libgme0
      - libgomp1
      - libgphoto2-6
      - libgphoto2-port12
      - libgraphite2-3
      - libgsm1
      - libharfbuzz0b
      - libicu66
      - libilmbase24
      - libjbig0
      - libjpeg-turbo8
      - libltdl7
      - libmodplug1
      - libmp3lame0
      - libogg0
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenexr24
      - libopenjp2-7
      - libopus0
      - liborc-0.4-0
      - libpixman-1-0
      - libprotobuf-lite17
      - libpython3.9
      - libraw1394-11
      - librtmp1
      - libschroedinger-coordgenlibs1
      - libschroedinger-maeparser1
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample3
      - libswscale5
      - libthai0
      - libtheora0
      - libtiff5
      - libtwolame0
      - libusb-1.0-0
      - libv4l-0
      - libv4lconvert0
      - libva2
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx6
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libwebp6
      - libx11-6
      - libx264-155
      - libx265-179
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxvidcore4
      - libzvbi0
      - python3-numpy
      - python3-minimal
      - libtesseract4
      - to amd64: [ "libcrystalhd3:amd64", "libnuma1:amd64" ]
      - to i386: [ "libcrystalhd3:i386", "libnuma1:i386" ]
  xwayland-kiosk-helper:
    plugin: nil
    stage-snaps: [mir-kiosk-x11]
  demos:
    plugin: dump
    source: demos

  facetracker:
    after: [ opencv ]
    plugin: cmake
    source: https://github.com/alfonsosanchezbeato/Single_Face_Tracking_using_5_inbuilt_OpenCV_trackers.git
    source-tag: master
    override-build: |
      cp ${SNAPCRAFT_PROJECT_DIR}/facetracker.cpp ${SNAPCRAFT_PART_SRC}/
      snapcraftctl build

  cascades:
    after: [ facetracker ]
    plugin: dump
    source: cascades
    organize:
      wrenches.xml: usr/share/opencv4/haarcascades/wrenches.xml

  v4l2-ctl:
    after: [ cascades ]
    plugin: nil
    stage-packages:
      - v4l-utils

  cleanup:
    after:
      - facetracker
    plugin: nil
    build-snaps:
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done  

